# Generated by Django 5.2.12 on 2026-05-19 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('post', models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='포스터')),
                ('director', models.CharField(max_length=100, verbose_name='감독')),
                ('genre', models.CharField(max_length=100, verbose_name='장르')),
                ('content', models.TextField(blank=True, null=True, verbose_name='내용')),
                ('release_date', models.DateField(verbose_name='개봉일')),
                ('is_seen', models.BooleanField(default=False, verbose_name='관람여부')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=10, verbose_name='평점')),
                ('content', models.TextField(verbose_name='감상평')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie', verbose_name='영화')),
            ],
        ),
    ]
