# Generated by Django 5.2.12 on 2026-04-08 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='제목')),
                ('post', models.ImageField(blank=True, null=True, upload_to='', verbose_name='포스터')),
                ('director', models.CharField(verbose_name='감독')),
                ('genre', models.CharField(verbose_name='장르')),
                ('content', models.TextField(blank=True, null=True, verbose_name='내용')),
                ('release_date', models.DateField(verbose_name='개봉일')),
                ('is_seen', models.BooleanField(default=False, verbose_name='관람여부')),
            ],
        ),
    ]
