# Generated by Django 5.2.12 on 2026-05-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='post',
            field=models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='포스터'),
        ),
    ]
