# Generated by Django 5.2.12 on 2026-04-11 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_director_alter_movie_genre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=10, verbose_name='평점')),
                ('content', models.TextField(verbose_name='감상평')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie', verbose_name='영화')),
            ],
        ),
    ]
